name: sign_language_flutter
description: A sign language learning application
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  mongo_dart: ^0.9.1
  crypto: ^3.0.3
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - .env